services:
  app:
    container_name: sports-maintenance-dashboard
    build:
      context: .
      target: development
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8001:8001"
