# Don't allow dependencies to be used before they have been released for at least 1 week
minimumReleaseAge: 10080

# Hoist all dependencies to the root of node_modules, for better compatibility with packages that expect flat node_modules
shamefullyHoist: true

overrides:
  serialize-javascript: ">=7.0.5"
  uuid: ">=11.1.1"

allowBuilds:
  core-js: true
  core-js-pure: true
  unrs-resolver: true
